services:
  - type: web
    name: gobackend
    env: python
    build:
      commands:
        - apt-get update && apt-get install -y python python-pip
        - pip install -r requirements.txt
    start: python soccer_scrape.py
    plan: free
    region: virginia
    branches:
      - main
